default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: "HAZX33F4T7",
      issuer_id: "fd4cca56-716b-4f03-8e44-de72a03453db",
      key_filepath: "./AuthKey_HAZX33F4T7.p8"
    )
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "Runner.xcodeproj",
    )
    # Step 2 - Download provisioning profiles and certificates
    match(
      readonly: true,
    )

    # Step 3 - Build the project
    build_app(
      archive_path: "../build/ios/archive/Runner.xcarchive",
      export_method: "app-store",
    )

    # Step 4 - Upload the project
    changelog_from_git_commits(
      date_format: "%Y-%m-%d",
    )
    upload_to_testflight(
      ipa: "./Runner.ipa",
    )
  end


  desc "Register Devices"
  lane :register_new_devices do
    # see the Apple Sample (http://devimages.apple.com/downloads/devices/Multiple-Upload-Samples.zip)
    register_devices(
      devices_file: "./fastlane/devices.txt",
      team_id: "CPL7H8SHVM"
    )
    match_after_register
  end

  desc "match_after_register"
  lane :match_after_register do
    # 前回との差分を見て，新しいデバイスが追加されているなら新しくprovisioning profileを作成する
    match(type: "develop", force_for_new_devices: true)
    match(type: "adhoc", force_for_new_devices: true)
    slack(message: "<@hoge> 新しい端末が登録されました！")
  end
end

